Repository jedzej/tietopythontraining-basic, pull requests merged in 2018-03, with the labels that each got.

#101 lesson_01 tasks
  students/jemielity_kamil/lesson_01_basics/README.md
  students/jemielity_kamil/lesson_01_basics/apple_sharing.py
  students/jemielity_kamil/lesson_01_basics/area_of_right_angled_traingle.py
  students/jemielity_kamil/lesson_01_basics/car_route.py
  students/jemielity_kamil/lesson_01_basics/clock_face_1.py
  students/jemielity_kamil/lesson_01_basics/digital_clock.py
  students/jemielity_kamil/lesson_01_basics/first_digit_after_decimal.py
  students/jemielity_kamil/lesson_01_basics/fractional_part.py
  students/jemielity_kamil/lesson_01_basics/hello_harry.py
  students/jemielity_kamil/lesson_01_basics/last_digit_of_integer.py
  students/jemielity_kamil/lesson_01_basics/previous_and_next.py
  students/jemielity_kamil/lesson_01_basics/school_desks.py
  students/jemielity_kamil/lesson_01_basics/sum_of_digits.py
  students/jemielity_kamil/lesson_01_basics/sum_of_three_numbers.py
  students/jemielity_kamil/lesson_01_basics/tens_digit.py
  students/jemielity_kamil/lesson_01_basics/total_cost.py
Labels: kamwar

#63 Lesson 01 python basic
  students/grzegorz_bajorski/lesson_01_python_basic/apple_sharing.py
  students/grzegorz_bajorski/lesson_01_python_basic/area_of_rihgt_angled_triangle.py
  students/grzegorz_bajorski/lesson_01_python_basic/car_route.py
  students/grzegorz_bajorski/lesson_01_python_basic/clock_face.py
  students/grzegorz_bajorski/lesson_01_python_basic/digital_clock.py
  students/grzegorz_bajorski/lesson_01_python_basic/first_digits_after_decimal_point.py
  students/grzegorz_bajorski/lesson_01_python_basic/fractional_part.py
  students/grzegorz_bajorski/lesson_01_python_basic/hallo_harry.py
  students/grzegorz_bajorski/lesson_01_python_basic/last_digit_of_intiger.py
  students/grzegorz_bajorski/lesson_01_python_basic/previous_and_next.py
  students/grzegorz_bajorski/lesson_01_python_basic/school_desks.py
  students/grzegorz_bajorski/lesson_01_python_basic/sum_of_digits.py
  students/grzegorz_bajorski/lesson_01_python_basic/sum_of_three_numbers.py
  students/grzegorz_bajorski/lesson_01_python_basic/tens_digit.py
  students/grzegorz_bajorski/lesson_01_python_basic/total_cost.py
Labels: gradopaw

#88 Add lesson_01 exercises
  students/piechowski.michal/lesson_01_basics/apple_sharing.py
  students/piechowski.michal/lesson_01_basics/area_of_right_angled_triangle.py
  students/piechowski.michal/lesson_01_basics/car_route.py
  students/piechowski.michal/lesson_01_basics/clock_face_1.py
  students/piechowski.michal/lesson_01_basics/clock_face_2.py
  students/piechowski.michal/lesson_01_basics/digital_clock.py
  students/piechowski.michal/lesson_01_basics/first_digit_after_decimal_point.py
  students/piechowski.michal/lesson_01_basics/fractional_part.py
  students/piechowski.michal/lesson_01_basics/hello_harry.py
  students/piechowski.michal/lesson_01_basics/last_digit_of_integer.py
  students/piechowski.michal/lesson_01_basics/previous_and_next.py
  students/piechowski.michal/lesson_01_basics/school_desks.py
  students/piechowski.michal/lesson_01_basics/sum_of_digits.py
  students/piechowski.michal/lesson_01_basics/sum_of_three_numbers.py
  students/piechowski.michal/lesson_01_basics/tens_digit.py
  students/piechowski.michal/lesson_01_basics/total_cost.py
Labels: kadilak83

#91 Lesson 1 solutions
  students/sikorski_marcin/Lesson_1_-_Python_basics.py
Labels: kadilak83

#83 Added lesson_01_basics practice projects
  students/swietczak_monika/lesson_01_basics/apple_sharing.py
  students/swietczak_monika/lesson_01_basics/area_of_right_angled_triangle.py
  students/swietczak_monika/lesson_01_basics/car_route.py
  students/swietczak_monika/lesson_01_basics/clock_face.py
  students/swietczak_monika/lesson_01_basics/digital_clock.py
  students/swietczak_monika/lesson_01_basics/first_digit_after_decimal_point.py
  students/swietczak_monika/lesson_01_basics/fractional_part.py
  students/swietczak_monika/lesson_01_basics/hello_harry.py
  students/swietczak_monika/lesson_01_basics/last_digit.py
  students/swietczak_monika/lesson_01_basics/previous_and_next.py
  students/swietczak_monika/lesson_01_basics/school_desks.py
  students/swietczak_monika/lesson_01_basics/sum_of_digits.py
  students/swietczak_monika/lesson_01_basics/sum_of_three_numbers.py
  students/swietczak_monika/lesson_01_basics/tens_digit.py
  students/swietczak_monika/lesson_01_basics/total_cost.py
Labels: kamwar

#117 complete lesson 1 tasks
  students/slawinski_amadeusz/lesson_01_basics/1.01_sum_of_three_numbers.py
  students/slawinski_amadeusz/lesson_01_basics/1.02_area_of_right-angled_triangle.py
  students/slawinski_amadeusz/lesson_01_basics/1.03_hello_harry.py
  students/slawinski_amadeusz/lesson_01_basics/1.04_apple_sharing.py
  students/slawinski_amadeusz/lesson_01_basics/1.05_previous_and_next.py
  students/slawinski_amadeusz/lesson_01_basics/1.06_school_desks.py
  students/slawinski_amadeusz/lesson_01_basics/2.01_last_digit_of_integer.py
  students/slawinski_amadeusz/lesson_01_basics/2.02_tens_digit.py
  students/slawinski_amadeusz/lesson_01_basics/2.03_sum_of_digits.py
  students/slawinski_amadeusz/lesson_01_basics/2.04_fractional_part.py
  students/slawinski_amadeusz/lesson_01_basics/2.05_first_digit_after_decimal_point.py
  students/slawinski_amadeusz/lesson_01_basics/2.06_car_route.py
  students/slawinski_amadeusz/lesson_01_basics/2.07_digital_clock.py
  students/slawinski_amadeusz/lesson_01_basics/2.08_total_cost.py
  students/slawinski_amadeusz/lesson_01_basics/2.09_clock_face_1.py
Labels: kadilak83

#122 Pull request for lesson 01
  students/serek_wojciech/lesson_01_basics/add_three.py
  students/serek_wojciech/lesson_01_basics/apple_sharing.py
  students/serek_wojciech/lesson_01_basics/area_of_triangle.py
  students/serek_wojciech/lesson_01_basics/car_route.py
  students/serek_wojciech/lesson_01_basics/clock_face.py
  students/serek_wojciech/lesson_01_basics/digit_after_decimal.py
  students/serek_wojciech/lesson_01_basics/digital_clock.py
  students/serek_wojciech/lesson_01_basics/fractional_part.py
  students/serek_wojciech/lesson_01_basics/hello_harry.py
  students/serek_wojciech/lesson_01_basics/last_digit_of_int.py
  students/serek_wojciech/lesson_01_basics/previous_and_next.py
  students/serek_wojciech/lesson_01_basics/shool_desks.py
  students/serek_wojciech/lesson_01_basics/sum_of_digits.py
  students/serek_wojciech/lesson_01_basics/tens_digit.py
  students/serek_wojciech/lesson_01_basics/total_cost.py
Labels: gradopaw

#72 Lesson 01 - 15 tasks
  students/nartowska_karina/lesson_01_basics/README.md
  students/nartowska_karina/lesson_01_basics/apple_sharing.py
  students/nartowska_karina/lesson_01_basics/area_of_right_angled_triangle.py
  students/nartowska_karina/lesson_01_basics/car_route.py
  students/nartowska_karina/lesson_01_basics/clock_face_1.py
  students/nartowska_karina/lesson_01_basics/digital_clock.py
  students/nartowska_karina/lesson_01_basics/first_digit_after_decimal_point.py
  students/nartowska_karina/lesson_01_basics/fractional_part.py
  students/nartowska_karina/lesson_01_basics/hello_harry.py
  students/nartowska_karina/lesson_01_basics/last_digit_of_integer.py
  students/nartowska_karina/lesson_01_basics/previous_and_next.py
  students/nartowska_karina/lesson_01_basics/school_desks.py
  students/nartowska_karina/lesson_01_basics/sum_of_digits.py
  students/nartowska_karina/lesson_01_basics/sum_of_three_numbers.py
  students/nartowska_karina/lesson_01_basics/tens_digit.py
  students/nartowska_karina/lesson_01_basics/total_cost.py
Labels: gradopaw

#106 Lession 01: BASIC
  students/kosarzewski_maciej/lesson_01_basics/apple_sharing.py
  students/kosarzewski_maciej/lesson_01_basics/area_of_right-angled_triangle.py
  students/kosarzewski_maciej/lesson_01_basics/car_route.py
  students/kosarzewski_maciej/lesson_01_basics/clock_face1.py
  students/kosarzewski_maciej/lesson_01_basics/digital_clock.py
  students/kosarzewski_maciej/lesson_01_basics/firs_dig_after_dec_point.py
  students/kosarzewski_maciej/lesson_01_basics/fractional_part.py
  students/kosarzewski_maciej/lesson_01_basics/hello_harry.py
  students/kosarzewski_maciej/lesson_01_basics/last_dig_of_integer.py
  students/kosarzewski_maciej/lesson_01_basics/previous_and_next.py
  students/kosarzewski_maciej/lesson_01_basics/school_desks.py
  students/kosarzewski_maciej/lesson_01_basics/sum_of_digits.py
  students/kosarzewski_maciej/lesson_01_basics/sum_of_three_numbers.py
  students/kosarzewski_maciej/lesson_01_basics/tens_digit.py
  students/kosarzewski_maciej/lesson_01_basics/total_cost.py
Labels: kamwar

#139 Add files to lesson 2
  students/grzegorz_bajorski/lesson_02_flow_control/adding_factorials.py
  students/grzegorz_bajorski/lesson_02_flow_control/bishop_move.py
  students/grzegorz_bajorski/lesson_02_flow_control/chocolate_bar.py
  students/grzegorz_bajorski/lesson_02_flow_control/factorial.py
  students/grzegorz_bajorski/lesson_02_flow_control/knight_move.py
  students/grzegorz_bajorski/lesson_02_flow_control/ladder.py
  students/grzegorz_bajorski/lesson_02_flow_control/leap_year.py
  students/grzegorz_bajorski/lesson_02_flow_control/lost_card.py
  students/grzegorz_bajorski/lesson_02_flow_control/queen_move.py
  students/grzegorz_bajorski/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
  students/grzegorz_bajorski/lesson_02_flow_control/the_number_of_zero.py
  students/grzegorz_bajorski/lesson_02_flow_control/the_second_maximum.py
Labels: gradopaw

#120 Solutions of problems from lesson 1
  students/pietrewicz_bartosz/lesson_01_basics/1_1.py
  students/pietrewicz_bartosz/lesson_01_basics/1_2.py
  students/pietrewicz_bartosz/lesson_01_basics/1_3.py
  students/pietrewicz_bartosz/lesson_01_basics/1_4.py
  students/pietrewicz_bartosz/lesson_01_basics/1_5.py
  students/pietrewicz_bartosz/lesson_01_basics/1_6.py
  students/pietrewicz_bartosz/lesson_01_basics/2_1.py
  students/pietrewicz_bartosz/lesson_01_basics/2_2.py
  students/pietrewicz_bartosz/lesson_01_basics/2_3.py
  students/pietrewicz_bartosz/lesson_01_basics/2_4.py
  students/pietrewicz_bartosz/lesson_01_basics/2_5.py
  students/pietrewicz_bartosz/lesson_01_basics/2_6.py
  students/pietrewicz_bartosz/lesson_01_basics/2_7.py
  students/pietrewicz_bartosz/lesson_01_basics/2_8.py
  students/pietrewicz_bartosz/lesson_01_basics/2_9.py
Labels: gradopaw

#159 Lesson_01: Solve all problems from Snakify lesson 01 and Snakify less…
  students/mitek_michal/lesson_01_basics/apple_sharing.py
  students/mitek_michal/lesson_01_basics/area_of_right_angled_triangle.py
  students/mitek_michal/lesson_01_basics/car_route.py
  students/mitek_michal/lesson_01_basics/clock_face.py
  students/mitek_michal/lesson_01_basics/digital_clock.py
  students/mitek_michal/lesson_01_basics/first_number_after_decimal_point.py
  students/mitek_michal/lesson_01_basics/fractional_part.py
  students/mitek_michal/lesson_01_basics/hello_harry.py
  students/mitek_michal/lesson_01_basics/last_digit_of_integer.py
  students/mitek_michal/lesson_01_basics/previous_and_next.py
  students/mitek_michal/lesson_01_basics/school_desks.py
  students/mitek_michal/lesson_01_basics/sum_of_digits.py
  students/mitek_michal/lesson_01_basics/sum_of_three_numbers.py
  students/mitek_michal/lesson_01_basics/tens_digit.py
  students/mitek_michal/lesson_01_basics/total_cost.py
Labels: gradopaw

#90 lesson_01
  students/jarosz_natalia/lesson_01/apple_sharing.py
  students/jarosz_natalia/lesson_01/area_of_right_angled_triangle.py
  students/jarosz_natalia/lesson_01/car_route.py
  students/jarosz_natalia/lesson_01/clock_face.py
  students/jarosz_natalia/lesson_01/digital_clock.py
  students/jarosz_natalia/lesson_01/first_digit_after_decimal_point.py
  students/jarosz_natalia/lesson_01/fractional_part.py
  students/jarosz_natalia/lesson_01/hello_harry.py
  students/jarosz_natalia/lesson_01/last_digit_of_integer.py
  students/jarosz_natalia/lesson_01/previous_and_next.py
  students/jarosz_natalia/lesson_01/school_desks.py
  students/jarosz_natalia/lesson_01/sum_of_digits.py
  students/jarosz_natalia/lesson_01/sum_of_three_numbers.py
  students/jarosz_natalia/lesson_01/tens_digit.py
  students/jarosz_natalia/lesson_01/total_cost.py
Labels: gradopaw

#66 lesson_01 problems solved
  students/kulon_aleksander/lesson_01/problem_apple_sharing.py
  students/kulon_aleksander/lesson_01/problem_area_of_right_angled_triangle.py
  students/kulon_aleksander/lesson_01/problem_car_route.py
  students/kulon_aleksander/lesson_01/problem_clock_face.py
  students/kulon_aleksander/lesson_01/problem_digital_clock.py
  students/kulon_aleksander/lesson_01/problem_first_digit_after_decimal_point.py
  students/kulon_aleksander/lesson_01/problem_hello_harry.py
  students/kulon_aleksander/lesson_01/problem_last_digit_of_integer.py
  students/kulon_aleksander/lesson_01/problem_previous_and_next.py
  students/kulon_aleksander/lesson_01/problem_school_desks.py
  students/kulon_aleksander/lesson_01/problem_sum_of_digits.py
  students/kulon_aleksander/lesson_01/problem_sum_of_three_numbers.py
  students/kulon_aleksander/lesson_01/problem_tens_digit.py
  students/kulon_aleksander/lesson_01/problem_total_cost.py
Labels: gradopaw

#127 Lesson_01: done excercises
  students/olszewski_bartosz/lesson_01_python_basics/Last_digit_of_integer.py
  students/olszewski_bartosz/lesson_01_python_basics/apple_sharing.py
  students/olszewski_bartosz/lesson_01_python_basics/area_of_right-angled_triangle.py
  students/olszewski_bartosz/lesson_01_python_basics/car_route.py
  students/olszewski_bartosz/lesson_01_python_basics/clock_face_1.py
  students/olszewski_bartosz/lesson_01_python_basics/digital_clock.py
  students/olszewski_bartosz/lesson_01_python_basics/first_digit_after_decimal_point.py
  students/olszewski_bartosz/lesson_01_python_basics/fractional_part.py
  students/olszewski_bartosz/lesson_01_python_basics/hello_harry!.py
  students/olszewski_bartosz/lesson_01_python_basics/previous_and_next.py
  students/olszewski_bartosz/lesson_01_python_basics/school_desks.py
  students/olszewski_bartosz/lesson_01_python_basics/sum_of_digits.py
  students/olszewski_bartosz/lesson_01_python_basics/sum_of_three_numbers.py
  students/olszewski_bartosz/lesson_01_python_basics/tens_digit.py
  students/olszewski_bartosz/lesson_01_python_basics/total_cost.py
Labels: kamwar

#138 Lesson 01
  students/grzegorz_kowalik/lesson_01_basics/apple_sharing.py
  students/grzegorz_kowalik/lesson_01_basics/area_of_triangle.py
  students/grzegorz_kowalik/lesson_01_basics/car_route.py
  students/grzegorz_kowalik/lesson_01_basics/clock_face.py
  students/grzegorz_kowalik/lesson_01_basics/digital_clock.py
  students/grzegorz_kowalik/lesson_01_basics/first_decimal_digit.py
  students/grzegorz_kowalik/lesson_01_basics/fractional_part.py
  students/grzegorz_kowalik/lesson_01_basics/hello_harry.py
  students/grzegorz_kowalik/lesson_01_basics/last_digit_of_integer.py
  students/grzegorz_kowalik/lesson_01_basics/previous_and_next.py
  students/grzegorz_kowalik/lesson_01_basics/school_desks.py
  students/grzegorz_kowalik/lesson_01_basics/sum_of_digits.py
  students/grzegorz_kowalik/lesson_01_basics/sum_of_three.py
  students/grzegorz_kowalik/lesson_01_basics/tens_digit.py
  students/grzegorz_kowalik/lesson_01_basics/total_cost.py
Labels: kadilak83

#156 Lesson 02 - solutions
  students/serek_wojciech/lesson_02_flow_control/adding_factorials.py
  students/serek_wojciech/lesson_02_flow_control/bishop_moves.py
  students/serek_wojciech/lesson_02_flow_control/chocolate_bar.py
  students/serek_wojciech/lesson_02_flow_control/elements_equal_maximum.py
  students/serek_wojciech/lesson_02_flow_control/factorial.py
  students/serek_wojciech/lesson_02_flow_control/knight_move.py
  students/serek_wojciech/lesson_02_flow_control/ladder.py
  students/serek_wojciech/lesson_02_flow_control/leap_year.py
  students/serek_wojciech/lesson_02_flow_control/lost_card.py
  students/serek_wojciech/lesson_02_flow_control/queen_move.py
  students/serek_wojciech/lesson_02_flow_control/the_number_of_zeros.py
  students/serek_wojciech/lesson_02_flow_control/the_second_maximum.py
Labels: gradopaw

#141 Lesson 01 completed - adding py files
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_01.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_02.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_03.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_04.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_05.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_06.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_07.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_08.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_09.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_10.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_01.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_02.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_03.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_04.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_05.py
  students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_06.py
Labels: kadilak83

#197 Solutions of the problems from lesson 2
  students/pietrewicz_bartosz/lesson_02_flow_control/Adding_factorials.py
  students/pietrewicz_bartosz/lesson_02_flow_control/Bishop_moves.py
  students/pietrewicz_bartosz/lesson_02_flow_control/Chocolate_bar.py
  students/pietrewicz_bartosz/lesson_02_flow_control/Factorial.py
  students/pietrewicz_bartosz/lesson_02_flow_control/Knight_move.py
  students/pietrewicz_bartosz/lesson_02_flow_control/Ladder.py
  students/pietrewicz_bartosz/lesson_02_flow_control/Leap_year.py
  students/pietrewicz_bartosz/lesson_02_flow_control/Lost_card.py
  students/pietrewicz_bartosz/lesson_02_flow_control/Queen_move.py
  students/pietrewicz_bartosz/lesson_02_flow_control/The_number_of_elements_equal_to_the_maximum.py
  students/pietrewicz_bartosz/lesson_02_flow_control/The_number_of_zeros.py
  students/pietrewicz_bartosz/lesson_02_flow_control/The_second_maximum.py
Labels: gradopaw

#189 Gradopaw/lesson 01 basics
  students/chylak_malgorzata/lesson_01_basics/apple_sharing.py
  students/chylak_malgorzata/lesson_01_basics/area_of_right-angled_triangle.py
  students/chylak_malgorzata/lesson_01_basics/car_route.py
  students/chylak_malgorzata/lesson_01_basics/clock_face.py
  students/chylak_malgorzata/lesson_01_basics/digital_clock.py
  students/chylak_malgorzata/lesson_01_basics/first_digit_after_decimal_point.py
  students/chylak_malgorzata/lesson_01_basics/fractional_part.py
  students/chylak_malgorzata/lesson_01_basics/hello_harry.py
  students/chylak_malgorzata/lesson_01_basics/last_digit_of_integer.py
  students/chylak_malgorzata/lesson_01_basics/previous_and_next.py
  students/chylak_malgorzata/lesson_01_basics/school_desks.py
  students/chylak_malgorzata/lesson_01_basics/sum_of_digits.py
  students/chylak_malgorzata/lesson_01_basics/sum_of_three_numbers.py
  students/chylak_malgorzata/lesson_01_basics/tens_digit.py
  students/chylak_malgorzata/lesson_01_basics/total_cost.py
Labels: gradopaw

#182 complete lesson 2 tasks
  students/slawinski_amadeusz/lesson_02_flow_control/3.01_bishop_moves.py
  students/slawinski_amadeusz/lesson_02_flow_control/3.02_queen_moves.py
  students/slawinski_amadeusz/lesson_02_flow_control/3.03_knight_moves.py
  students/slawinski_amadeusz/lesson_02_flow_control/3.04_chocolate_bar.py
  students/slawinski_amadeusz/lesson_02_flow_control/3.05_leap_year.py
  students/slawinski_amadeusz/lesson_02_flow_control/4.01_factorial.py
  students/slawinski_amadeusz/lesson_02_flow_control/4.02_the_number_of_zeros.py
  students/slawinski_amadeusz/lesson_02_flow_control/4.03_adding_factorials.py
  students/slawinski_amadeusz/lesson_02_flow_control/4.04_ladder.py
  students/slawinski_amadeusz/lesson_02_flow_control/4.05_lost_card.py
  students/slawinski_amadeusz/lesson_02_flow_control/6.01_the_second_maximum.py
  students/slawinski_amadeusz/lesson_02_flow_control/6.02_the_number_of_elements_equal_to_the_maximum.py
Labels: kadilak83

#217 Lesson 02 completed - adding py files
  students/piotrowski_stanislaw/lesson_02_flow_control/bishop_move.py
  students/piotrowski_stanislaw/lesson_02_flow_control/chocolate.py
  students/piotrowski_stanislaw/lesson_02_flow_control/factorial.py
  students/piotrowski_stanislaw/lesson_02_flow_control/how_many_zeroes.py
  students/piotrowski_stanislaw/lesson_02_flow_control/knight_move.py
  students/piotrowski_stanislaw/lesson_02_flow_control/ladder.py
  students/piotrowski_stanislaw/lesson_02_flow_control/leap_year.py
  students/piotrowski_stanislaw/lesson_02_flow_control/lost_card.py
  students/piotrowski_stanislaw/lesson_02_flow_control/queen_move.py
  students/piotrowski_stanislaw/lesson_02_flow_control/seq_num_maximal.py
  students/piotrowski_stanislaw/lesson_02_flow_control/seq_second_max.py
  students/piotrowski_stanislaw/lesson_02_flow_control/sum_of_factorials.py
Labels: kadilak83

#125 Lesson 01:
  students/stachowska_agata/lesson_01_basics/01Lesson.py
Labels: kamwar

#170 Gradopaw/lesson 01 basics
  students/saleta_sebastian/lesson_01_basics/apple_sharing.py
  students/saleta_sebastian/lesson_01_basics/area_of_right_angle_triangle.py
  students/saleta_sebastian/lesson_01_basics/car_route.py
  students/saleta_sebastian/lesson_01_basics/clock_face_1.py
  students/saleta_sebastian/lesson_01_basics/clock_face_2.py
  students/saleta_sebastian/lesson_01_basics/digital_clock.py
  students/saleta_sebastian/lesson_01_basics/first_digit_after_decimal_point.py
  students/saleta_sebastian/lesson_01_basics/fractional_part.py
  students/saleta_sebastian/lesson_01_basics/hello_harry.py
  students/saleta_sebastian/lesson_01_basics/last_digit_of_integer.py
  students/saleta_sebastian/lesson_01_basics/previous_and_next.py
  students/saleta_sebastian/lesson_01_basics/problem_01.py
  students/saleta_sebastian/lesson_01_basics/school_desks.py
  students/saleta_sebastian/lesson_01_basics/sum_of_digits.py
  students/saleta_sebastian/lesson_01_basics/sum_of_three_numbers.py
  students/saleta_sebastian/lesson_01_basics/tens_digit.py
  students/saleta_sebastian/lesson_01_basics/total_cost.py
Labels: gradopaw

#161 Lesson_03 - solutions
  students/serek_wojciech/lesson_03_functions/calculator.py
  students/serek_wojciech/lesson_03_functions/collatz_and_input_validation.py
  students/serek_wojciech/lesson_03_functions/exponentiation.py
  students/serek_wojciech/lesson_03_functions/fibonacci_numbers.py
  students/serek_wojciech/lesson_03_functions/length_of_the_segment.py
  students/serek_wojciech/lesson_03_functions/negative_exponent.py
Labels: gradopaw

#244 Lesson 02 - 12 tasks
  students/nartowska_karina/lesson_02_flow_control/README.md
  students/nartowska_karina/lesson_02_flow_control/adding_factorials.py
  students/nartowska_karina/lesson_02_flow_control/bishop_moves.py
  students/nartowska_karina/lesson_02_flow_control/chocolate_bar.py
  students/nartowska_karina/lesson_02_flow_control/factorial.py
  students/nartowska_karina/lesson_02_flow_control/knight_move.py
  students/nartowska_karina/lesson_02_flow_control/ladder.py
  students/nartowska_karina/lesson_02_flow_control/leap_year.py
  students/nartowska_karina/lesson_02_flow_control/lost_card.py
  students/nartowska_karina/lesson_02_flow_control/queen_move.py
  students/nartowska_karina/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
  students/nartowska_karina/lesson_02_flow_control/the_number_of_zeros.py
  students/nartowska_karina/lesson_02_flow_control/the_second_maximum.py
Labels: gradopaw

#246 Gradopaw/lesson 02 flow control
  students/saleta_sebastian/lesson_02_flow_control/adding_factorials.py
  students/saleta_sebastian/lesson_02_flow_control/bishop_moves.py
  students/saleta_sebastian/lesson_02_flow_control/chocolate_bar.py
  students/saleta_sebastian/lesson_02_flow_control/factorial.py
  students/saleta_sebastian/lesson_02_flow_control/knight_moves.py
  students/saleta_sebastian/lesson_02_flow_control/ladder.py
  students/saleta_sebastian/lesson_02_flow_control/leap_year.py
  students/saleta_sebastian/lesson_02_flow_control/lost_card.py
  students/saleta_sebastian/lesson_02_flow_control/queen_move.py
  students/saleta_sebastian/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
  students/saleta_sebastian/lesson_02_flow_control/the_number_of_zeros.py
  students/saleta_sebastian/lesson_02_flow_control/the_second_maximum.py
Labels: gradopaw

#242 Gradopaw/lesson 02
  students/kulon_aleksander/lesson_02/adding_factorials.py
  students/kulon_aleksander/lesson_02/bishop_move.py
  students/kulon_aleksander/lesson_02/chocolate_bar.py
  students/kulon_aleksander/lesson_02/factorial.py
  students/kulon_aleksander/lesson_02/knight_move.py
  students/kulon_aleksander/lesson_02/ladder.py
  students/kulon_aleksander/lesson_02/lap_year.py
  students/kulon_aleksander/lesson_02/lost_card.py
  students/kulon_aleksander/lesson_02/queen_move.py
  students/kulon_aleksander/lesson_02/the_number_of_elements_equal_to_the_maximum.py
  students/kulon_aleksander/lesson_02/the_number_of_zeroes.py
  students/kulon_aleksander/lesson_02/the_second_maximum.py
Labels: gradopaw

#221 Lesson_02: Solve all problems from Snakify lesson 01 and Snakify less…
  students/mitek_michal/lesson_02_flow_control/bishop_move.py
  students/mitek_michal/lesson_02_flow_control/chocolate_bar.py
  students/mitek_michal/lesson_02_flow_control/factorial.py
  students/mitek_michal/lesson_02_flow_control/knight_move.py
  students/mitek_michal/lesson_02_flow_control/ladder.py
  students/mitek_michal/lesson_02_flow_control/leap_year.py
  students/mitek_michal/lesson_02_flow_control/lost_card.py
  students/mitek_michal/lesson_02_flow_control/number_of_elements_equalt_to_the_maximum.py
  students/mitek_michal/lesson_02_flow_control/number_of_zeroes.py
  students/mitek_michal/lesson_02_flow_control/queen_move.py
  students/mitek_michal/lesson_02_flow_control/second_maximum.py
  students/mitek_michal/lesson_02_flow_control/sum_of_factorials.py
Labels: gradopaw

#270 Solutions for problems from lesson 03
  students/pietrewicz_bartosz/lesson_03_functions/calculator.py
  students/pietrewicz_bartosz/lesson_03_functions/exponentation.py
  students/pietrewicz_bartosz/lesson_03_functions/fibonacci_numbers.py
  students/pietrewicz_bartosz/lesson_03_functions/input_validation.py
  students/pietrewicz_bartosz/lesson_03_functions/negative_exponent.py
  students/pietrewicz_bartosz/lesson_03_functions/the_collatz_sequence.py
  students/pietrewicz_bartosz/lesson_03_functions/the_length_of_the_segment.py
Labels: gradopaw

#286 lesson_04_unit_testing: solutions
  students/serek_wojciech/lesson_03_functions/__init__.py
  students/serek_wojciech/lesson_04_unit_testing/__init__.py
  students/serek_wojciech/lesson_04_unit_testing/test_collatz.py
  students/serek_wojciech/lesson_04_unit_testing/test_distance.py
  students/serek_wojciech/lesson_04_unit_testing/test_fib_numbers.py
Labels: gradopaw

#254 Lesson 3 - 6 tasks
  students/nartowska_karina/lesson_03_functions/calculator.py
  students/nartowska_karina/lesson_03_functions/exponentiation.py
  students/nartowska_karina/lesson_03_functions/fibonacci_numbers.py
  students/nartowska_karina/lesson_03_functions/negative_exponent.py
  students/nartowska_karina/lesson_03_functions/the_collatz_sequence_and_input_validation.py
  students/nartowska_karina/lesson_03_functions/the_length_of_the_segment.py
Labels: gradopaw

#158 Lesson 3 add files
  students/grzegorz_bajorski/lesson_03_functions/calculator.py
  students/grzegorz_bajorski/lesson_03_functions/exponentiation.py
  students/grzegorz_bajorski/lesson_03_functions/fibonacci_numbers.py
  students/grzegorz_bajorski/lesson_03_functions/input_validation.py
  students/grzegorz_bajorski/lesson_03_functions/negative_exponent.py
  students/grzegorz_bajorski/lesson_03_functions/the_collatz_seq.py
  students/grzegorz_bajorski/lesson_03_functions/the_length_of_the_segment.py
Labels: gradopaw

#292 Gradopaw/lesson 02
  students/jarosz_natalia/lesson_02/adding_factorials.py
  students/jarosz_natalia/lesson_02/bishop_moves.py
  students/jarosz_natalia/lesson_02/chocolate_bar.py
  students/jarosz_natalia/lesson_02/factorial.py
  students/jarosz_natalia/lesson_02/knight_move.py
  students/jarosz_natalia/lesson_02/ladder.py
  students/jarosz_natalia/lesson_02/leap_year.py
  students/jarosz_natalia/lesson_02/lost_card.py
  students/jarosz_natalia/lesson_02/queen_move.py
  students/jarosz_natalia/lesson_02/the_number_of_elements_equal_to_the_maximum.py
  students/jarosz_natalia/lesson_02/the_number_of_zeros.py
  students/jarosz_natalia/lesson_02/the_second_maximum.py
Labels: gradopaw

#289 flow_control_solutions
  students/chylak_malgorzata/lesson_02_flow_control/adding_factorials.py
  students/chylak_malgorzata/lesson_02_flow_control/bishop_moves.py
  students/chylak_malgorzata/lesson_02_flow_control/chocolate_bar.py
  students/chylak_malgorzata/lesson_02_flow_control/factorial.py
  students/chylak_malgorzata/lesson_02_flow_control/knight_move.py
  students/chylak_malgorzata/lesson_02_flow_control/ladder.py
  students/chylak_malgorzata/lesson_02_flow_control/leap_year.py
  students/chylak_malgorzata/lesson_02_flow_control/lost_card.py
  students/chylak_malgorzata/lesson_02_flow_control/queen_move.py
  students/chylak_malgorzata/lesson_02_flow_control/the_number_of_elements_equal_to_maximum.py
  students/chylak_malgorzata/lesson_02_flow_control/the_number_of_zeros.py
  students/chylak_malgorzata/lesson_02_flow_control/the_second_maximum.py
Labels: gradopaw

#327 Add lesson_04_unit_testing solutions
  students/ryba_paula/lesson_04_unit_tests/fibonacci_numbers.py
  students/ryba_paula/lesson_04_unit_tests/test_collatz.py
  students/ryba_paula/lesson_04_unit_tests/test_distance.py
  students/ryba_paula/lesson_04_unit_tests/test_fibonacci.py
  students/ryba_paula/lesson_04_unit_tests/the_collatz_sequence_and_validation.py
  students/ryba_paula/lesson_04_unit_tests/the_length_of_the_segment.py
Labels: kadilak83
