Repository jedzej/tietopythontraining-basic, pull requests merged in 2018-06, with the labels that each got.

#424 Lesson 06 initial commit
  students/grzegorz_bajorski/lesson_06/access_rights.py
  students/grzegorz_bajorski/lesson_06/cities.py
  students/grzegorz_bajorski/lesson_06/cubes.py
  students/grzegorz_bajorski/lesson_06/fantasy_game.py
  students/grzegorz_bajorski/lesson_06/fantasy_game_add.py
  students/grzegorz_bajorski/lesson_06/frequency_analysis.py
  students/grzegorz_bajorski/lesson_06/guess_number.py
  students/grzegorz_bajorski/lesson_06/inspect_args.py
  students/grzegorz_bajorski/lesson_06/logger_wraper.py
  students/grzegorz_bajorski/lesson_06/reverse_seq.py
  students/grzegorz_bajorski/lesson_06/sum_all.py
  students/grzegorz_bajorski/lesson_06/the_number_of_distinct.py
  students/grzegorz_bajorski/lesson_06/uppercases.py
Labels: gradopaw

#560 Lesson 10 - All tasks
  students/kaczmarek_katarzyna/lesson_10_organizing_files/deleting_unneeded_files.py
  students/kaczmarek_katarzyna/lesson_10_organizing_files/filling_in_the_gaps.py
  students/kaczmarek_katarzyna/lesson_10_organizing_files/selective_copy.py
Labels: kadilak83

#544 complete lesson 7 tasks
  students/slawinski_amadeusz/lesson_07_string_datetime/05_replace_the_substring.py
  students/slawinski_amadeusz/lesson_07_string_datetime/05_the_number_of_words.py
  students/slawinski_amadeusz/lesson_07_string_datetime/05_to_saw_the_two_words.py
  students/slawinski_amadeusz/lesson_07_string_datetime/date_calculator.py
  students/slawinski_amadeusz/lesson_07_string_datetime/date_printer.py
  students/slawinski_amadeusz/lesson_07_string_datetime/delta_time_calculator.py
  students/slawinski_amadeusz/lesson_07_string_datetime/table_printer.py
  students/slawinski_amadeusz/lesson_07_string_datetime/timestamp_to_date.py
Labels: kadilak83

#551 Add lesson09 solutions
  students/ryba_paula/lesson_09_reading_and_writing_files/extending_the_multiclipboard.pyw
  students/ryba_paula/lesson_09_reading_and_writing_files/file.txt
  students/ryba_paula/lesson_09_reading_and_writing_files/mad_libs.py
  students/ryba_paula/lesson_09_reading_and_writing_files/regex_search.py
  students/ryba_paula/lesson_09_reading_and_writing_files/test.txt
Labels: kadilak83

#546 Lesson 06 solutions
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/__init__.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/access_rights.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/args_inspector.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/args_sum.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/countries_and_cities.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/cubes.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/fantasy_game_inventory.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/frequency_analysis.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/guess_the_number.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/list_to_dictionary_function_for_fantasy_game_inventory.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/logger_wrapper.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/reverse_the_sequence.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/the_number_of_distinct_words_in_some_text.py
  students/chylak_malgorzata/lesson_06_dictionaries_tuples_and_sets/uppercase.py
Labels: gradopaw

#566 Gradopaw/lesson 07 manipulating strings
  students/chylak_malgorzata/lesson_07_manipulating_strings_+_datetime_formatting/date_calculator.py
  students/chylak_malgorzata/lesson_07_manipulating_strings_+_datetime_formatting/date_printer.py
  students/chylak_malgorzata/lesson_07_manipulating_strings_+_datetime_formatting/delta_time_calculator.py
  students/chylak_malgorzata/lesson_07_manipulating_strings_+_datetime_formatting/replace_the_substring.py
  students/chylak_malgorzata/lesson_07_manipulating_strings_+_datetime_formatting/table_printer.py
  students/chylak_malgorzata/lesson_07_manipulating_strings_+_datetime_formatting/the_number_of_words.py
  students/chylak_malgorzata/lesson_07_manipulating_strings_+_datetime_formatting/timestampt_to_date.py
  students/chylak_malgorzata/lesson_07_manipulating_strings_+_datetime_formatting/to_swap_the_two_words.py
Labels: gradopaw

#522 Lesson 6 Dictionaries
  students/olszewski_bartosz/lesson_06_dictionaries/acces_rights.py
  students/olszewski_bartosz/lesson_06_dictionaries/args_inspector.py
  students/olszewski_bartosz/lesson_06_dictionaries/args_sum.py
  students/olszewski_bartosz/lesson_06_dictionaries/cities_and_countires.py
  students/olszewski_bartosz/lesson_06_dictionaries/cubes.py
  students/olszewski_bartosz/lesson_06_dictionaries/fantasy_game_inventiry_add_new_items.py
  students/olszewski_bartosz/lesson_06_dictionaries/fantasy_game_inventory.py
  students/olszewski_bartosz/lesson_06_dictionaries/frequency_analysis.py
  students/olszewski_bartosz/lesson_06_dictionaries/guess_the_number.py
  students/olszewski_bartosz/lesson_06_dictionaries/logger_wrapper.py
  students/olszewski_bartosz/lesson_06_dictionaries/reverse_the_sequence.py
  students/olszewski_bartosz/lesson_06_dictionaries/the_number_of_distinct_words_in_some_text.py
  students/olszewski_bartosz/lesson_06_dictionaries/uppercase.py
Labels: waiting

#576 Add lesson 10 solutions
  students/ryba_paula/lesson_10_organizing_files/deleting_unneeded_files.py
  students/ryba_paula/lesson_10_organizing_files/filling_the_gaps.py
  students/ryba_paula/lesson_10_organizing_files/selective_copy.py
Labels: kadilak83

#579 Add lesson 11 solutions
  students/ryba_paula/lesson_11_argparse_and_math/filling_the_gaps_arg.py
  students/ryba_paula/lesson_11_argparse_and_math/regex_search_arg.py
  students/ryba_paula/lesson_11_argparse_and_math/selective_copy_arg.py
Labels: kadilak83

#519 Kamwar/lesson 10 organizing files
  students/jemielity_kamil/lesson_10_organizing_files/deleting_unneeded_files.py
  students/jemielity_kamil/lesson_10_organizing_files/filling_in_the_gaps.py
  students/jemielity_kamil/lesson_10_organizing_files/selective_copy.py
Labels: waiting

#494 Kamwar/lesson 09 reading and writing files
  students/jemielity_kamil/lesson_09_reading_and_writing_files/extending_the_multiclipboard.pyw
  students/jemielity_kamil/lesson_09_reading_and_writing_files/mad_libs
  students/jemielity_kamil/lesson_09_reading_and_writing_files/mad_libs.py
  students/jemielity_kamil/lesson_09_reading_and_writing_files/regex_search.py
Labels: waiting

#596 Add lesson 12 solutions
  students/ryba_paula/lesson_12_debugging/debugging_coin_toss.py
  students/ryba_paula/lesson_12_debugging/validated_user_base.py
  students/ryba_paula/lesson_12_debugging/validators.py
  students/ryba_paula/lesson_12_debugging/verbose_output.py
Labels: kadilak83

#543 Add lesson 10
  students/nartowska_karina/lesson_10_organizing_files/deleting_unneeded_files.py
  students/nartowska_karina/lesson_10_organizing_files/filling_in_the_gaps.py
  students/nartowska_karina/lesson_10_organizing_files/selective_copy.py
Labels: gradopaw

#627 lesson_10
  students/chylak_malgorzata/lesson_10_organizing_files/deleting_unneeded_files.py
  students/chylak_malgorzata/lesson_10_organizing_files/filling_in_the_gaps.py
  students/chylak_malgorzata/lesson_10_organizing_files/selective_copy.py
Labels: gradopaw
