Repository jedzej/tietopythontraining-basic, pull requests merged in 2018-07, with the labels that each got.

#605 Add lesson_13 exercises
  students/piechowski_michal/lesson_13_objects_and_classes/circle_class.py
  students/piechowski_michal/lesson_13_objects_and_classes/object_inspector_1.py
  students/piechowski_michal/lesson_13_objects_and_classes/object_inspector_2.py
  students/piechowski_michal/lesson_13_objects_and_classes/selective_shallow_compare.py
Labels: kadilak83

#538 Added lesson 08 solutions
  students/swietczak_monika/lesson_08_regular_expressions/email_validator.py
  students/swietczak_monika/lesson_08_regular_expressions/phone_number_validator.py
  students/swietczak_monika/lesson_08_regular_expressions/postal_code_validator.py
  students/swietczak_monika/lesson_08_regular_expressions/regex_version_of_strip.py
  students/swietczak_monika/lesson_08_regular_expressions/strong_password_detection.py
Labels: waiting

#643 Add lesson 14 solutions
  students/ryba_paula/lesson_14_decorators/access_required.py
  students/ryba_paula/lesson_14_decorators/authorization.py
  students/ryba_paula/lesson_14_decorators/logged.py
  students/ryba_paula/lesson_14_decorators/sort.py
Labels: kadilak83

#561 Grzegorz.bajorski/lesson 08 regular expressions
  students/grzegorz_bajorski/lesson_08_regular_expressions/Email_validator.py
  students/grzegorz_bajorski/lesson_08_regular_expressions/Regex_version_of_strip.py
  students/grzegorz_bajorski/lesson_08_regular_expressions/Strong_password.py
  students/grzegorz_bajorski/lesson_08_regular_expressions/phone_number_validation.py
  students/grzegorz_bajorski/lesson_08_regular_expressions/postal_code.py
Labels: gradopaw

#562 Grzegorz.bajorski/lesson 09 extending the multiclipboard
  students/grzegorz_bajorski/lesson_09_extending_the_multiclipboard/input.txt
  students/grzegorz_bajorski/lesson_09_extending_the_multiclipboard/mad_libs.py
  students/grzegorz_bajorski/lesson_09_extending_the_multiclipboard/mcb
  students/grzegorz_bajorski/lesson_09_extending_the_multiclipboard/mcb.pyw
  students/grzegorz_bajorski/lesson_09_extending_the_multiclipboard/regex_search.py
Labels: gradopaw
