Repository jedzej/tietopythontraining-basic, pull requests merged in 2018-05, with the labels that each got.

#489 Add lesson 8
  students/nartowska_karina/lesson_08_regular_expressions/email_validator.py
  students/nartowska_karina/lesson_08_regular_expressions/phone_number_validator.py
  students/nartowska_karina/lesson_08_regular_expressions/postal_code_validator.py
  students/nartowska_karina/lesson_08_regular_expressions/regex_version_of_strip.py
  students/nartowska_karina/lesson_08_regular_expressions/strong_password_detection.py
Labels: gradopaw

#329 unit tests added
  students/grzegorz_kowalik/lesson_03_functions/distance.py
  students/grzegorz_kowalik/lesson_03_functions/fibonacci.py
  students/grzegorz_kowalik/lesson_04_unit_testing/.gitignore
  students/grzegorz_kowalik/lesson_04_unit_testing/collatz_test.py
  students/grzegorz_kowalik/lesson_04_unit_testing/distance_test.py
  students/grzegorz_kowalik/lesson_04_unit_testing/fibonacci_test.py
Labels: kadilak83

#440 Results of lesson 05
  students/saleta_sebastian/lesson_05_lists/age_calculator.py
  students/saleta_sebastian/lesson_05_lists/character_picture_grid.py
  students/saleta_sebastian/lesson_05_lists/character_picture_grid.pyc
  students/saleta_sebastian/lesson_05_lists/chess_board.py
  students/saleta_sebastian/lesson_05_lists/comma_code.py
  students/saleta_sebastian/lesson_05_lists/comma_code.pyc
  students/saleta_sebastian/lesson_05_lists/diagonal_parallel.py
  students/saleta_sebastian/lesson_05_lists/greater_than_neighbours.py
  students/saleta_sebastian/lesson_05_lists/maximum.py
  students/saleta_sebastian/lesson_05_lists/numbers_filter.py
  students/saleta_sebastian/lesson_05_lists/numbers_filter.pyc
  students/saleta_sebastian/lesson_05_lists/swap_min_and_max.py
  students/saleta_sebastian/lesson_05_lists/the_bowling_alley.py
Labels: gradopaw

#504 Gradopaw/lesson 06
  students/kulon_aleksander/lesson_06/access_rights.py
  students/kulon_aleksander/lesson_06/args_inspector.py
  students/kulon_aleksander/lesson_06/args_sum.py
  students/kulon_aleksander/lesson_06/countries_and_cities.py
  students/kulon_aleksander/lesson_06/cubes.py
  students/kulon_aleksander/lesson_06/fantasy_game_inventory.py
  students/kulon_aleksander/lesson_06/frequency_analysis.py
  students/kulon_aleksander/lesson_06/guess_the_number.py
  students/kulon_aleksander/lesson_06/list_to_dictionary_function.py
  students/kulon_aleksander/lesson_06/logger_wrapper.py
  students/kulon_aleksander/lesson_06/reverse_the_sequence.py
  students/kulon_aleksander/lesson_06/the_number_of_distinct_words.py
  students/kulon_aleksander/lesson_06/uppercase.py
Labels: gradopaw

#497 Solve all problems from lesson 06
  students/mitek_michal/lesson_06_dictionares_tuples_sets/__init__.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/access_rigths.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/args_inspector.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/args_sum.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/countries_and_cities.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/cubes.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/fantasy_game_inventory.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/frequency_analysis.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/guess_the_number.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/logger_wrapper.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/reverse_the_sequence.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/the_number_of_distinct_words_in_some_text.py
  students/mitek_michal/lesson_06_dictionares_tuples_sets/uppercase.py
Labels: gradopaw

#517 Gradopaw/lesson 07
  students/kulon_aleksander/lesson_07/data_printer.py
  students/kulon_aleksander/lesson_07/date_calculator.py
  students/kulon_aleksander/lesson_07/delta_time_calculator.py
  students/kulon_aleksander/lesson_07/replace_the_substring.py
  students/kulon_aleksander/lesson_07/table_printer.py
  students/kulon_aleksander/lesson_07/the_number_of_words.py
  students/kulon_aleksander/lesson_07/timestamp_to_date.py
  students/kulon_aleksander/lesson_07/to_swap_the_two_words.py
Labels: gradopaw

#513 Add lesson_09 exercises
  students/piechowski_michal/lesson_09_reading_and_writing_files/extending_the_multiclipboard.pyw
  students/piechowski_michal/lesson_09_reading_and_writing_files/mad_libs.py
  students/piechowski_michal/lesson_09_reading_and_writing_files/mad_libs_text.txt
  students/piechowski_michal/lesson_09_reading_and_writing_files/regex_search.py
Labels: kadilak83

#347 Kamwar/lesson 04 unit testing
  students/Hebdowska_Grazyna/lesson_04_uni_testing/.pytest_cache/v/cache/nodeids
  students/Hebdowska_Grazyna/lesson_04_uni_testing/pytest_testing_distance.py
  students/Hebdowska_Grazyna/lesson_04_uni_testing/pytest_testing_fibonacci.py
  students/Hebdowska_Grazyna/lesson_04_uni_testing/unit_testing_collatz.py
  students/Hebdowska_Grazyna/lesson_04_uni_testing/unit_testing_distance.py
  students/Hebdowska_Grazyna/lesson_04_uni_testing/unit_testing_fibonacci.py
Labels: waiting

#418 Lesson 6
  students/Hebdowska_Grazyna/lesson_06/access_right.py
  students/Hebdowska_Grazyna/lesson_06/add_to_inventory.py
  students/Hebdowska_Grazyna/lesson_06/arg_sum.py
  students/Hebdowska_Grazyna/lesson_06/countries_and_cites.py
  students/Hebdowska_Grazyna/lesson_06/cubes.py
  students/Hebdowska_Grazyna/lesson_06/frequency_analysis.py
  students/Hebdowska_Grazyna/lesson_06/guess_the_number.py
  students/Hebdowska_Grazyna/lesson_06/inspect_args.py
  students/Hebdowska_Grazyna/lesson_06/inventory.py
  students/Hebdowska_Grazyna/lesson_06/logger_wrapper.py
  students/Hebdowska_Grazyna/lesson_06/reverse.py
  students/Hebdowska_Grazyna/lesson_06/the_number_of_distinct_words_in_some_test.py
  students/Hebdowska_Grazyna/lesson_06/uppercase.py
Labels: waiting

#447 Added lesson_06 solutions
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/guess_the_number.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/inventory.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/list_to_dictionary.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/the_number_of_distinct_words.py
  students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py
Labels: waiting

#456 lessosn_05_lists
  students/olszewski_bartosz/lesson_05_lists/character_picture_grid.py
  students/olszewski_bartosz/lesson_05_lists/chess_board.py
  students/olszewski_bartosz/lesson_05_lists/comma code.py
  students/olszewski_bartosz/lesson_05_lists/greater_than_neighbours.py
  students/olszewski_bartosz/lesson_05_lists/maximum.py
  students/olszewski_bartosz/lesson_05_lists/numbers_filter.py
  students/olszewski_bartosz/lesson_05_lists/swap_min_and_max.py
  students/olszewski_bartosz/lesson_05_lists/the_bowling_alley.py
  students/olszewski_bartosz/lesson_05_lists/the_diagonal_parallel_to_the_main.py
Labels: waiting

#474 complete lesson 06 tasks
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/08_reverse_the_sequence.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/08_uppercase.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/10_cubes.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/10_guess_the_number.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/10_the_number_of_distinct_words_in_some_text.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/11_access_rights.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/11_countries_and_cities.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/11_frequency_analysis.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/inventory.py
  students/slawinski_amadeusz/lesson_06_dicts_tuples_sets_args_kwargs/logger_wrapper.py
Labels: kadilak83
